"""rm_optional

Revision ID: cb9c121ea3dd
Revises: d05d5b7d204e
Create Date: 2024-03-19 17:37:48.557177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb9c121ea3dd'
down_revision: Union[str, None] = 'd05d5b7d204e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('images', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('images', 'byte_image_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('images', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('images', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('images_title_key', 'images', type_='unique')
    op.create_index(op.f('ix_images_title'), 'images', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_title'), table_name='images')
    op.create_unique_constraint('images_title_key', 'images', ['title'])
    op.alter_column('images', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('images', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('images', 'byte_image_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('images', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('images', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
